apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    environment: development
    owner: team-alpha
  annotations:
    description: "Namespace for development workloads"
    contact: "patel.developer@gmail.com"
