apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: nginx
  labels:
    app: nginx
    environment: development
    owner: team-alpha
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
