kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.33.0
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP # Optional, defaults to tcp
      # listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    - containerPort: 443
      hostPort: 443
      protocol: TCP # Optional, defaults to tcp
      # listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
  - role: worker
    image: kindest/node:v1.33.0
  - role: worker
    image: kindest/node:v1.33.0
  - role: worker
    image: kindest/node:v1.33.0
